export type SampleDataItem = {
  id: number;
  slug: string;
  url: string;
  client: string;
  location: string;
  date: string;
  images: string[];
};
export type SampleDataType = SampleDataItem[];

export const sampleData: SampleDataType = [
  {
    id: 1,
    slug: "parda",
    url: "/assets/images/img1.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img2.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img3.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img4.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img5.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img6.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img7.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img8.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img9.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img10.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img11.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img12.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img13.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "parda",
    url: "/assets/images/img14.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
     {
    id: 2,
    slug: "parda",
    url: "/assets/images/img15.jpeg",
    client: "Prada",
    location: "Milan,IT",
    date: "2022",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
];
