export type SampleDataItem = {
  id: number;
  slug: string;
  url: string;
  client: string;
  location: string;
  date: string;
  images: string[];
};

export type SampleDataType = SampleDataItem[];

export const sampleData: SampleDataType = [
  {
    id: 1,
    slug: "Lipstick",
    url: "/assets/images/img1.jpeg",
    client: "MoMA",
    location: "New York, US",
    date: "2024",
    images: [
      "/assets/images/Lipstick1.jpeg",
      "/assets/images/Lipstick2.jpeg",
      "/assets/images/Lipstick3.jpeg",
      "/assets/images/Lipstick4.jpeg",
      "/assets/images/Lipstick5.jpeg",
    ],
  },
  {
    id: 2,
    slug: "Perfume",
    url: "/assets/images/Perfume0.jpeg",
    client: "The New Yorker",
    location: "Brooklyn, US",
    date: "2023",
    images: [
      "/assets/images/Perfume1.jpeg",
      "/assets/images/Perfume2.jpeg",
      "/assets/images/Perfume3.jpeg",
      "/assets/images/Perfume4.jpeg",
      "/assets/images/Perfume5.jpeg",
    ],
  },
  {
    id: 3,
    slug: "Coffee",
    url: "/assets/images/Coffee0.jpeg",
    client: "Aesop",
    location: "Los Angeles, US",
    date: "2024",
    images: [
      "/assets/images/Coffee1.jpeg",
      "/assets/images/Coffee2.jpeg",
      "/assets/images/Coffee3.jpeg",
      "/assets/images/Coffee4.jpeg",
      "/assets/images/Coffee5.jpeg",
    ],
  },
  {
    id: 4,
    slug: "Vehicle",
    url: "/assets/images/Vehicle0.jpeg",
    client: "COS",
    location: "San Francisco, US",
    date: "2023",
    images: [
      "/assets/images/Vehicle1.jpeg",
      "/assets/images/Vehicle2.jpeg",
      "/assets/images/Vehicle3.jpeg",
      "/assets/images/Vehicle4.jpeg",
      "/assets/images/Vehicle5.jpeg",
    ],
  },
  {
    id: 5,
    slug: "Wooden",
    url: "/assets/images/Wooden0.jpeg",
    client: "Chanel",
    location: "Paris, FR",
    date: "2024",
    images: [
      "/assets/images/Wooden1.jpeg",
      "/assets/images/Wooden2.jpeg",
      "/assets/images/Wooden3.jpeg",
      "/assets/images/Wooden4.jpeg",
      "/assets/images/Wooden5.jpeg",
    ],
  },
  {
    id: 6,
    slug: "Chair",
    url: "/assets/images/Chair0.jpeg",
    client: "Vogue US",
    location: "New York, US",
    date: "2024",
    images: [
      "/assets/images/Chair1.jpeg",
      "/assets/images/Chair2.jpeg",
      "/assets/images/Chair3.jpeg",
      "/assets/images/Chair4.jpeg",
      "/assets/images/Chair5.jpeg",
    ],
  },
  {
    id: 7,
    slug: "MinimalistChair",
    url: "/assets/images/MinimalistChair0.jpeg",
    client: "Yves Saint Laurent",
    location: "Los Angeles, US",
    date: "2024",
    images: [
      "/assets/images/MinimalistChair1.jpeg",
      "/assets/images/MinimalistChair2.jpeg",
      "/assets/images/MinimalistChair3.jpeg",
      "/assets/images/MinimalistChair4.jpeg",
      "/assets/images/MinimalistChair5.jpeg",
    ],
  },
  {
    id: 8,
    slug: "Glass",
    url: "/assets/images/Glass0.jpeg",
    client: "Kinfolk",
    location: "Portland, US",
    date: "2023",
    images: [
      "/assets/images/Glass1.jpeg",
      "/assets/images/Glass2.jpeg",
      "/assets/images/Glass3.jpeg",
      "/assets/images/Glass4.jpeg",
      "/assets/images/Glass5.jpeg",
    ],
  },
  {
    id: 9,
    slug: "Sculptures",
    url: "/assets/images/Sculptures0.jpeg",
    client: "T Magazine",
    location: "New York, US",
    date: "2023",
    images: [
      "/assets/images/Sculptures1.jpeg",
      "/assets/images/Sculptures2.jpeg",
      "/assets/images/Sculptures3.jpeg",
      "/assets/images/Sculptures4.jpeg",
      "/assets/images/Sculptures5.jpeg",
    ],
  },
  {
    id: 10,
    slug: "Water",
    url: "/assets/images/Water0.jpeg",
    client: "Nike",
    location: "Portland, US",
    date: "2024",
    images: [
      "/assets/images/Water1.jpeg",
      "/assets/images/Water2.jpeg",
      "/assets/images/Water3.jpeg",
      "/assets/images/Water4.jpeg",
      "/assets/images/Water5.jpeg",
    ],
  },
  {
    id: 11,
    slug: "Human",
    url: "/assets/images/Human0.jpeg",
    client: "Gagosian",
    location: "Los Angeles, US",
    date: "2024",
    images: [
      "/assets/images/Human1.jpeg",
      "/assets/images/Human2.jpeg",
      "/assets/images/Human3.jpeg",
      "/assets/images/Human4.jpeg",
      "/assets/images/Human5.jpeg",
    ],
  },
  {
    id: 12,
    slug: "AbstractGlass",
    url: "/assets/images/AbstractGlass0.jpeg",
    client: "Apartamento",
    location: "Barcelona, ES",
    date: "2023",
    images: [
      "/assets/images/AbstractGlass1.jpeg",
      "/assets/images/AbstractGlass2.jpeg",
      "/assets/images/AbstractGlass3.jpeg",
      "/assets/images/AbstractGlass4.jpeg",
      "/assets/images/AbstractGlass5.jpeg",
    ],
  },
  {
    id: 13,
    slug: "Vase",
    url: "/assets/images/Vase0.jpeg",
    client: "The Whitney",
    location: "New York, US",
    date: "2023",
    images: [
      "/assets/images/Vase1.jpeg",
      "/assets/images/Vase2.jpeg",
      "/assets/images/Vase3.jpeg",
      "/assets/images/Vase4.jpeg",
      "/assets/images/Vase5.jpeg",
    ],
  },
  {
    id: 14,
    slug: "Table",
    url: "/assets/images/Table0.jpeg",
    client: "Loewe",
    location: "Madrid, ES",
    date: "2024",
    images: [
      "/assets/images/Table1.jpeg",
      "/assets/images/Table2.jpeg",
      "/assets/images/Table3.jpeg",
      "/assets/images/Table4.jpeg",
      "/assets/images/Table5.jpeg",
    ],
  },
  {
    id: 15,
    slug: "Flower",
    url: "/assets/images/Flower0.jpeg",
    client: "Chanel",
    location: "Paris, FR",
    date: "2023",
    images: [
      "/assets/images/Flower1.jpeg",
      "/assets/images/Flower2.jpeg",
      "/assets/images/Flower3.jpeg",
      "/assets/images/Flower4.jpeg",
      "/assets/images/Flower5.jpeg",
    ],
  },
];
